version: "3.8"

networks:
  traefik:
    external: true

volumes:
  nextcloud-data:
    name: nextcloud-data
    driver: local
  nextcloud-db-data:
    name: nextcloud-db-data
    driver: local

services:
  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    networks:
      - traefik
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - NEXTCLOUD_ADMIN=$NEXTCLOUD_ADMIN
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_HOST
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`$NEXTCLOUD_HOST`)
      - traefik.http.routers.nextcloud.service=nextcloud-service
      - traefik.http.services.nextcloud-service.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.entrypoints=websecure

  nextcloud-cron:
      image: nextcloud:29.0.0-apache
      entrypoint: /cron.sh
      networks:
        - traefik
      volumes:
        - nextcloud-data:/var/www/html
      depends_on:
        - nextcloud-db
        - nextcloud-cache
        - nextcloud

  nextcloud-db:
    container_name: nextcloud-db
    networks:
      - traefik
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_USER=$MYSQL_USER

  nextcloud-cache:
    networks:
      - traefik
      