version: "3.8"

services:
  nextcloud:
    image: nextcloud:29.0.1-apache
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-cache
    volumes:
      - ./setup-nextcloud.sh:/docker-entrypoint-hooks.d/post-installation/setup-nextcloud.sh
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - REDIS_HOST=nextcloud-cache
      - PHP_UPLOAD_LIMIT=1000M

  nextcloud-db:
    image: mysql:8.4.0
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-cache:
    image: redis:7.2.4
    container_name: nextcloud-cache
    hostname: nextcloud-cache
    restart: unless-stopped